# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
sphinx:
  configuration: docs/conf.py
python:  # See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
