name: unittests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        run: tox -e check
  test-38-and-others:
    # Reference: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        # Reference: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#running-tests-with-tox
        # Reference: https://tox.wiki/en/latest/development.html#running-tests
        run: tox -e ${{ matrix.python-version }}
  test-39-plus:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "pypy3.9", "pypy3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        # Reference: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#running-tests-with-tox
        # Reference: https://tox.wiki/en/latest/development.html#running-tests
        run: tox -e ${{ matrix.python-version }}
